application: hyrize-development
version: 1
runtime: php55
instance_class: F4_1G
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: /favicon.ico
  upload: /favicon.ico
  expiration: 30d

# make the user_guide a static dir!
# you dont need to include it in every project you make
- url: /user_guide
  static_dir: user_guide
- url: /assets
  static_dir: assets
- url: /uploads
  static_dir: uploads
- url: /.*
  script: index.php
